# Generated by Django 5.1 on 2024-10-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='images/categories/default.webp', null=True, upload_to='images/categories/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/products/default.webp', null=True, upload_to='images/products/'),
        ),
    ]
