# Generated by Django 5.1 on 2024-10-30 05:06

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_manufacturer_product_manufactures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='name',
        ),
        migrations.CreateModel(
            name='ManufacturerTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.manufacturer')),
            ],
            options={
                'verbose_name': 'Ishlab chiqaruvchi Translation',
                'db_table': 'catalog_manufacturer_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
