# Generated by Django 5.1 on 2025-01-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_manufacturer_name_manufacturertranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories/thumbnails/'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/thumbnails/'),
        ),
    ]
