# Generated by Django 5.1 on 2025-01-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_pdf_alter_categorytranslation_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
