# Generated by Django 5.1 on 2025-01-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_producttranslation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
